// <auto-generated />
namespace FMS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BM2505Container : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BM2505Container));
        
        string IMigrationMetadata.Id
        {
            get { return "202305100709213_BM2505Container"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
